### ISSUE TITLE
Transpiled version is not included in the npm package

### ISSUE THREAD

**Issue by SimonSelg** [kriasoft/node-sqlite#1]
Hey,

the field "main" in package.json points to `lib/index.js`, which does not exist in the npm package.

The field should be either changed to `src/index.js` (which is not good tho, because the babel require hook excludes files in the node_modules folder by default from transpiling) or the transpiled version should be included in the npm package.

Regards,
Simon

**Comment by koistya** [comment]
@SimonSelg thanks for the report!
