### ISSUE TITLE
db.serialize is needed

### ISSUE THREAD

**Issue by halaei** [kriasoft/node-sqlite#102]
I am using this for mocking a react-native sqlite driver. So I need all the database operations to be serialized, by calling db.serialize() without callback after opening the database. This is supported in sqlite3 package. How can I do the same here?

**Comment by halaei** [comment]
It seems db.driver.serialize() can do that.

**Comment by patarapolw** [comment]
Typescript definition won't allow that. I have to use `.getDatabaseInstance()` instead of `.driver`
