### ISSUE TITLE
No support for node v13

### ISSUE THREAD

**Issue by DV54321** [kriasoft/node-sqlite#103]
There is no support for node v13

**Comment by theogravity** [comment]
what happens when you try node v13 - saying there's no support doesn't help here. Give some logs.

**Comment by theogravity** [comment]
Please re-open if after trying out v4 that it is an issue specific to `sqlite` and not `sqlite3`.

**Comment by theogravity** [comment]
According to the `sqlite3` repo, v13 is not supported:

https://github.com/mapbox/node-sqlite3#supported-platforms
