### ISSUE TITLE
Is this library alive?

### ISSUE THREAD

**Issue by cleoold** [kriasoft/node-sqlite#104]
Not intended to be rude, but I've seen this library has been inactive for a while and issues are unanswered. I know probably this library is a 'wrapper' that doesn't really that much updates, but I just want to be sure it is safe to use it.

**Comment by theogravity** [comment]
Depends on what your definition of safe is. 

- Does it pass `npm audit` for non-dev deps? Yes.
- it uses the latest sqlite3 under the hood
- Has this library been audited for security issues? I don't think so.

**Comment by theogravity** [comment]
There's also a v4 beta that I've just released - please check that one out!
