### ISSUE TITLE
TypeScript compiler errors on import

### ISSUE THREAD

**Issue by jameswilddev** [kriasoft/node-sqlite#107]
Hello!  Just about to go to bed, so probably tired and doing something silly.

When I try and use this from a TypeScript project (just importing the module https://github.com/jameswilddev/failed-install-repro/blob/master/index.ts), I see the following:

```
Module '"D:/a/failed-install-repro/failed-install-repro/node_modules/@types/sqlite3/index"' has no default export. Did you mean to use 'import { sqlite3 } from "D:/a/failed-install-repro/failed-install-repro/node_modules/@types/sqlite3/index"' instead?
```

(repro repository at: https://github.com/jameswilddev/failed-install-repro/runs/561090339?check_suite_focus=true)

Additionally, I had to add a dependency on `sql-template-strings` as its types were required by node-sqlite.

**Comment by theogravity** [comment]
I'll take a look - I didn't have any problems when trying it out on my own projects, but maybe I overlooked something

**Comment by theogravity** [comment]
Oh, I know what it is - make sure to read the project readme. I'm not sure if you're aware that v4 was just published. The usage is different, and you need to install `sqlite3` along with `sqlite`.

**Comment by theogravity** [comment]
I do see a bug with not having template strings installed, ill fix that

**Comment by theogravity** [comment]
Ok, this should be fixed now. 

No longer need to include `sql-template-strings`.

You do need to have `sqlite3` installed, however, since you will need to inject it as a driver into the `sqlite` library (see this project readme on usage).

**Comment by jameswilddev** [comment]
Thank you!
