### ISSUE TITLE
column index out of range when reading from db 

### ISSUE THREAD

**Issue by mmoomocow** [kriasoft/node-sqlite#111]
this is the code I have to read from my database

```js
new Promise((resolve, reject) => {
    db.each(
        'SELECT * from moderation WHERE userID = ?',
        [user.id],
        (err, row) => {
            if (err) {
                console.log(err)
                reject(err)
            }
            else {
                console.log(row)
            }
        },
        (err, _) => {
            if (err) {
                reject(err)
            } 
            else {
                resolve()
            }
        }
    )
}).then(
    message.channel.send(embed)
)
```

whenever I run it it gives the error
```[Error: SQLITE_RANGE: column index out of range] {
  errno: 25,
  code: 'SQLITE_RANGE'
}
```

How do I stop this error and get it to return the `row` correctly

**Comment by theogravity** [comment]
If you run the query via `db.all()` or `.row()`, do you get the same error? The code looks right to me (our unit tests show that a like-query passes).

I also noticed there's this issue too on the sqlite3 repo:

https://github.com/mapbox/node-sqlite3/issues/999

**Comment by theogravity** [comment]
I think I know what's wrong. Your fourth parameter / second callback. It doesn't exist in this library. 

The second callback is actually the result of the call to `each()`. See the readme:

https://github.com/kriasoft/node-sqlite#each

And the impl for this:

https://github.com/kriasoft/node-sqlite/blob/master/src/Database.ts#L186

If you are still having an issue, I would check that `user.id` actually has a value. If not that, then this might be a bug with `sqlite` as reported by:

https://github.com/mapbox/node-sqlite3/issues/999

**Comment by mmoomocow** [comment]
working now, I've used sqlite3 lots so must have done that accidentally

**Comment by theogravity** [comment]
I'll add some kind of guard for this, like throw an error of two callbacks are found. Thanks for your help!

**Comment by theogravity** [comment]
Addressed in https://github.com/kriasoft/node-sqlite/commit/ee59e5e868105819b2d00e235d19c0a20031c6f9
