### ISSUE TITLE
Import CSV?

### ISSUE THREAD

**Issue by geo-systems** [kriasoft/node-sqlite#114]
Hi team,

I went through the documentation, but couldn't find a way to import a CSV via this library.

Is there a way to invoke the `.import` special command via the library?

**Comment by theogravity** [comment]
If the `sqlite3` library supports it, we can as well, but need the documentation to know how to do the implementation.

If you can point out the documentation, I can look into it.

**Comment by theogravity** [comment]
Closing as this is more for the `sqlite3` library and this project is designed to wrap around it.
