### ISSUE TITLE
names import of sqlite does not work with nodes build in ESM modules

### ISSUE THREAD

**Issue by arlac77** [kriasoft/node-sqlite#116]
When trying to use node build in ESM support the following error occurs:

node sample.mjs

sample.mjs
```js
import sqlite3 from 'sqlite3'
import { open } from 'sqlite'
```

```
import { open } from 'sqlite'
         ^^^^
SyntaxError: The requested module 'sqlite' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
```

**Comment by theogravity** [comment]
if you modify the `index.js` of the sqlite package to `export default`, does it work?

**Comment by arlac77** [comment]
An additional line like
```js
exports.default = open;
```
does not change the outcome

**Comment by theogravity** [comment]
I'm happy to accept a PR that resolves your issue if you can figure out the proper fix.

**Comment by arlac77** [comment]
Probably cleanest way is to compile twice once with target CJS and another one with ESM;
then export both as described here:
[Conditional Exports](https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_conditional_exports).
If You are fine with that I can give it a try

**Comment by theogravity** [comment]
Would all files have to be compiled twice, or just the entrypoint? Concerned about package size.

**Comment by arlac77** [comment]
[PR-117](https://github.com/kriasoft/node-sqlite/pull/117)

**Comment by theogravity** [comment]
Merged and published, thanks!
