### ISSUE TITLE
Install of Babel needed? 

### ISSUE THREAD

**Issue by johan974** [kriasoft/node-sqlite#12]
When trying your sqlite package, I run into issues with Babel. 
ReferenceError: babelHelpers is not definedCan you help? 

More specific: 
C:\Users\Johan\node_only\node-sqlite\node_modules\sqlite\legacy.js:39
  babelHelpers.createClass(Statement, [{
  ^
ReferenceError: babelHelpers is not defined

On my windows, I see Node.js versin 4.4.7. 
npm install -g babel-cli. 
Same error applies.

**Comment by koistya** [comment]
Good catch, perhaps we need to disable this flag for `legacy.js` build:

https://github.com/kriasoft/node-sqlite/blob/master/tools/build.js#L37

**Comment by johan974** [comment]
Thanks for the quick reply. Can you signal me when I can retry? 
I am really looking forward to using your sqlite module.

**Comment by johan974** [comment]
Can you give me a signal when I can retry? 
Thank you in advance.

**Comment by robsonbittencourt** [comment]
Any news @koistya ?

**Comment by koistya** [comment]
@johan974 @robsonbittencourt this should be fixed now in `v2.2.3` (aa4e7244e8c0f9dff7b42bc1f506593b933a0772). Please, re-open if it doesn't work for you.

**Comment by robsonbittencourt** [comment]
@koistya thanks for your fast response. But i got another error now:

```
/home/robson/dev/hubot.js/node_modules/sqlite/legacy.js:609
      var _ref2 = asyncToGenerator(regeneratorRuntime.mark(function _callee() {
                                   ^

ReferenceError: regeneratorRuntime is not defined
    at /home/robson/dev/hubot.js/node_modules/sqlite/legacy.js:609:36
    at /home/robson/dev/hubot.js/node_modules/sqlite/legacy.js:937:6
    at Object.<anonymous> (/home/robson/dev/hubot.js/node_modules/sqlite/legacy.js:940:2)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

**Comment by sedenardi** [comment]
I'm also encountering the same error as @robsonbittencourt mentioned in the previous reply on v4.3.2, whereas it works just fine on v6.9.2. This prevents using this module in the AWS Lambda environment, as the version of Node is fixed to v4.

**Comment by rtran9** [comment]
same issue for me on  v4.8.0

**Comment by berndsummerswell** [comment]
> `ReferenceError: regeneratorRuntime is not defined`

I've got the same issue on 4.8.x

**Comment by theogravity** [comment]
can you give me more details about your env?

**Comment by berndsummerswell** [comment]
@theogravity In my case we have a requirement to still support some customers on WindowsXP - the latest LTS is 4.8.7. I am running with `--harmony` flag. What I have done in the meantime is just used the sqlite3 package (which works fine) and added promises myself.
