### ISSUE TITLE
Unable to open db

### ISSUE THREAD

**Issue by fs1995** [kriasoft/node-sqlite#121]
I am trying to run this query inside of an async function isInstalled():
`const result = await db.get('SELECT * FROM config')`

But if I open the database like this:
```
const sqlite3 = require('sqlite3');
const { open } = require('sqlite')
const db = open({
  filename: config.sqlite.file,
  driver: sqlite3.Database,
  verbose: true
}).then(isInstalled())
```
Then I get this error:
`ReferenceError: Cannot access 'db' before initialization`

Or if I open the database like this:
```
const sqlite3 = require('sqlite3');
const sqlite = require('sqlite');
const db = sqlite.open({
  filename: config.sqlite.file,
  driver: sqlite3.Database,
  verbose: true
})
isInstalled()
```

I get this:
`TypeError: db.get is not a function`

Not sure why this isin't working, seems like my code is running before the db gets to open?

**Comment by scsper** [comment]
hi @fs1995,

try 

```
const sqlite3 = require('sqlite3');
const { open } = require('sqlite')
const db = open({
  filename: config.sqlite.file,
  driver: sqlite3.Database,
  verbose: true
}).then(() => isInstalled())
```

or 

```
const sqlite3 = require('sqlite3');
const { open } = require('sqlite')
const db = open({
  filename: config.sqlite.file,
  driver: sqlite3.Database,
  verbose: true
}).then(isInstalled)
```

note that `.then` accepts a callback.  when the code you pasted executes, it will execute the `isInstalled()` function and expecting it to return a callback.  however, it errors because db is not initialized.

**Comment by fs1995** [comment]
That didn't work to make the db object globally accessibly, but I figured it out:
```
open({
  filename: config.sqlite.file,
  driver: sqlite3.Database,
  verbose: true
}).then((value) => {
  global.db = value
  isInstalled()
})
```
