### ISSUE TITLE
Make down migrations optional

### ISSUE THREAD

**Issue by PaulKiddle** [kriasoft/node-sqlite#128]
Thanks for the work on this nice library.

My method of data migration is to take a backup before running migrations, and restore the backup if there's a problem with the data, since up migrations can be lossy and down migrations won't necessarily be able to restore the data as it was previously.

With that in mind, can you please add the ability to use migration files that don't specify down migrations? Currently I am just adding a `-- Down` section with no content., which seems redundant.

If you're concerned about a developer accidentally forgetting to specify a down migration, it may be worth adding an `upOnly` option to the migration function to make sure this is intentional.

**Comment by theogravity** [comment]
I'm completely open to having it be optional. PRs with tests are welcomed!
