### ISSUE TITLE
does it work with idb-file-storage : https://www.npmjs.com/package/idb-file-storage

### ISSUE THREAD

**Issue by AbhinavAtul** [kriasoft/node-sqlite#130]
can `open` from `sqlite` be configured to work with idb-file-storage + cached.Database? I am new to typescript and trying to figure out if this module is only a server side or can be embedded in Angular webapps for offlining

`import sqlite3 from 'sqlite3'
import { open } from 'sqlite'

(async () => {
    const db = await open({
      _**filesytem: new IdbFileStorage()**_
      filename: '/tmp/database.db',
      driver: sqlite3.cached.Database
    })
})()
`

**Comment by theogravity** [comment]
This is a question for the `sqlite3` project, not this one.
