### ISSUE TITLE
Migrations Documentation

### ISSUE THREAD

**Issue by dschinkel** [kriasoft/node-sqlite#134]
The migration docs in here don't really explain the underlying mechanism for managing versions in migrations.  It barely touches the surface here.  Where can I find more details about what this API does under the hood?  I have no idea how it's picking up latest versions other than you showing to append some kind of number to files...that's not enough to understand the mechanism under the hood on how your API works.

And what about these scenarios:

- tell it to apply only a certain migration version
- tell it to apply the latest migration
- tell it to apply one or more specific versions

I guess in most scenarios it makes sense for **all** migrations to run on a new instance of the DB to get one up to the latest version of the DB.  And then new migrations picked up as you add them.

**Comment by dschinkel** [comment]
I think I [found most my answers](https://github.com/kriasoft/node-sqlite/blob/5d092c5844fa7a096d1539da91713232152cde5a/src/Database.js#L148-L150) with the exception of the ability to apply specific migrations or range rather than just latest

**Comment by theogravity** [comment]
You're welcome to submit a PR that improves on the documentation. This feature has been around for years and this is the first query regarding its usage. With respect to the tests, that's a fair amount of tests; again, you're welcome to contribute to them as well if you do not think they are sufficient.

**Comment by theogravity** [comment]
@dschinkel You're looking at the v3 code - why not use v4?

**Comment by dschinkel** [comment]
even this is lacking https://github.com/kriasoft/node-sqlite#migrations
