### ISSUE TITLE
json1 extension

### ISSUE THREAD

**Issue by fs1995** [kriasoft/node-sqlite#136]
Hello,

Is the json1 extension supported? If so, could a couple examples be added to the documentation?

**Comment by theogravity** [comment]
This library wraps around 'sqlite3', which according to this should be:

https://github.com/mapbox/node-sqlite3#features

Based on this article, it seems they are functions used within your sql statement and not called directly as part of an API directly against a class.

http://blog.benjamin-encz.de/post/sqlite-one-to-many-json1-extension/
