### ISSUE TITLE
Best way to batch create/insert or update? (How to properly use driver.serialize?)

### ISSUE THREAD

**Issue by patarapolw** [kriasoft/node-sqlite#137]
I am concerned about speed, actually. It matters when you commit too often.

My solution, but I haven't tested yet, looks like this. But I am not sure when to use `driver.parallelize()` (is it safe for writing?).

```ts
    const driver = db.getDatabaseInstance()

    await new Promise<void>((resolve, reject) => {
      driver.serialize(async () => {
        try {
          const stmt = driver.prepare(/* sql */ '')

          driver.exec('BEGIN TRANSACTION')

          items.map((it) => {
            stmt.run(it)
          })

          driver.exec('COMMIT')
          resolve()
        } catch (e) {
          driver.exec('ROLLBACK TRANSACTION')
          reject(e)
        }
      })
    })
```

If I had used `better-sqlite3`, it would be easy; but Electron on Windows won't allow it...

**Comment by theogravity** [comment]
This should be asked in the `sqlite3` repo instead as it deals with the driver directly:

https://github.com/mapbox/node-sqlite3

This library doesn't have direct async methods for serialize.

If you're concerned about speed, you should use this library instead:

https://github.com/JoshuaWise/better-sqlite3
