### ISSUE TITLE
SQLITE_ERROR not being rejected?

### ISSUE THREAD

**Issue by TenaciousDEK** [kriasoft/node-sqlite#14]
Hi,
I'm wondering if this is a bug with either node-sql or possibly the underlying node-sqlite3 perhaps?

In experimenting with transactions on multiple connections I ran the following test in mocha, which appears to pass with no errors. I'm basically creating two database connections but trying to begin successive transactions on just one of them, in order to force an error (which is why I'm using db1 twice rather than db2). Worryingly, the code below appears to pass with no errors shown!

Sqlite naturally balks at this and if you were to trap the error on 'transactDatabases' on the Promise.all with a .catch, it would correctly show the following error:-

`{ Error: SQLITE_ERROR: cannot start a transaction within a transaction
    at Error (native) errno: 1, code: 'SQLITE_ERROR' }`

The issue is though that I can't seem to trap this error in mocha as the Promise.all() doesn't appear to be rejected. It should be sufficient in mocha for me to return the rejected transactDatabases promise I would have thought?

Is this an error coming from Sqlite that's not being caught by the javascript libraries? Or more likely, as I'm just starting out in Javascript, am I doing something very wrong here?

The full test code is shown below...

```
import sqlite from 'sqlite';

describe('Sqlite', () => {
  describe('Can instantiate multiple database connections', () => {
    it.only('Can handle multiple isolated transactions', () => {
      const openDatabases = Promise.resolve()
      .then(() => Promise.all([
        sqlite.open(':memory:', { Promise }),
        sqlite.open(':memory:', { Promise }),
      ]));

      const transactDatabases = openDatabases
      .then(([db1, db2]) => {
        Promise.all([
          db1.run('BEGIN IMMEDIATE TRANSACTION'),
          db1.run('BEGIN IMMEDIATE TRANSACTION'),
        ]);
      });
      return transactDatabases;
    });
  });
});
```

Thanks!

Derek

**Comment by wmertens** [comment]
Agreed, I would expect sqlite to reject if sqlite3 throws. Since sqlite3 is in maintenance mode, I doubt they'll change sqlite3 to pass all errors to the callback, so it's up to sqlite to restore sanity.

**Comment by dmm** [comment]
Hey Derek, I think you've fallen into a very common trap for newcomers to promises. Promises don't throw normal exceptions, you have to add an explicit .catch block to your promise chain to catch rejections. If you don't have a .catch, your exceptions will silently swallowed!

Helpfully recent versions of node will output a warning in this situation:

`(node:25399) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: SQLITE_ERROR: cannot start a transaction within a transaction`

Check out this similar code that correctly catches the rejection:

```
const sqlite = require('sqlite');                                                                                                                             
                                                                                                                                                              
const openDatabases = Promise.all([                                                                                                                           
  sqlite.open(':memory:', { Promise }),                                                                                                                       
  sqlite.open(':memory:', { Promise }),                                                                                                                       
]);                                                                                                                                                           
                                                                                                                                                              
const transactDatabases = openDatabases                                                                                                                       
        .then(([db1, db2]) => {                                                                                                                               
          return Promise.all([                                                                                                                                
            db1.run('BEGIN IMMEDIATE TRANSACTION'),                                                                                                           
            db1.run('BEGIN IMMEDIATE TRANSACTION'),                                                                                                           
          ]);                                                                                                                                                 
        }).catch((error) => {                                                                                                                                 
          console.log('Caught an error! ' + error);                                                                                                           
        });
```
Printing:
`Caught an error! Error: SQLITE_ERROR: cannot start a transaction within a transaction`

This is one of the primary motivations behind the async/await syntax. I found this article to be a big help to understanding promises: https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html

Out of curiosity I've looked at the [relevant sqlite3 code](https://github.com/mapbox/node-sqlite3/blob/7322ea714b13451bab75d5232a1dd2a05fcb5052/src/statement.cc#L472). They check for SQLITE_ROW or SQLITE_DONE result codes and return an error in all other cases. So it appears they are properly sending errors.

**Comment by claudiopro** [comment]
I second @dmm's concerns and started seeing similar issues when handling `SQLITE_BUSY` errors in adelia:

https://travis-ci.org/emeraldion/adelia/jobs/185238161#L542 (Node 6.9)

```
(node:1686) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: SQLITE_BUSY: database is locked
```

https://travis-ci.org/emeraldion/adelia/jobs/185238159#L540 (Node 7.2)

```
(node:1686) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: SQLITE_BUSY: database is locked
(node:1686) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm more than happy to look into this :smile:
