### ISSUE TITLE
Can't execute transaction

### ISSUE THREAD

**Issue by hannahscript** [kriasoft/node-sqlite#144]
Hello, I am trying to run the following code using sqlite3 as a driver and sql-template-strings:

```javascript
const sql = SQL`begin transaction; update wallets set balance = iif((select balance from wallets where user_id = ${originUserId}) < ${amount}, balance, balance + ${amount}) where user_id = ${targetUserId}; update wallets set balance = iif(balance < ${amount}, balance, balance - ${amount}) where user_id = ${originUserId}; commit`;
        console.log('sql', sql);
        await this.db.run(sql);```

// Output is:

```sql SQLStatement {
  strings: [
    'begin transaction; update wallets set balance = iif((select balance from wallets where user_id = ',
    ') < ',
    ', balance, balance + ',
    ') where user_id = ',
    '; update wallets set balance = iif(balance < ',
    ', balance, balance - ',
    ') where user_id = ',
    '; commit'
  ],
  values: [
    '277146459080491008',
    10,
    10,
    '282581505996357632',
    10,
    10,
    '277146459080491008'
  ]
}
Error: SQLITE_RANGE: column index out of range
--> in Database#run('begin transaction; update wallets set balance = iif((select balance from wallets where user_id = ?) < ?, balance, balance + ?) where user_id = ?; update wallets set balance = iif(balance < ?, balance, balanc
e - ?) where user_id = ?; commit', '277146459080491008', 10, 10, '282581505996357632', 10, 10, '277146459080491008', [Function (anonymous)])
    at X:\Labor\hanabi\node_modules\sqlite\build\Database.js:95:21
    at new Promise (<anonymous>)
    at Database.run (X:\Labor\hanabi\node_modules\sqlite\build\Database.js:93:16)
    at CurrencyService.<anonymous> (X:\Labor\hanabi\build\services\currency-service.js:55:27)
    at Generator.next (<anonymous>)
    at X:\Labor\hanabi\build\services\currency-service.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (X:\Labor\hanabi\build\services\currency-service.js:4:12)
    at CurrencyService.transfer (X:\Labor\hanabi\build\services\currency-service.js:46:16) {
  errno: 25,
  code: 'SQLITE_RANGE',
  __augmented: true
}
``` 

I have also tried with db.exec instead of run and the output is:

``` 
[... same sql statement ...]

TRACE begin transaction;
TRACE update wallets set balance = iif((select balance from wallets where user_id = NULL) < NULL, balance, balance + NULL) where user_id = NULL;
TRACE update wallets set balance = iif(balance < NULL, balance, balance - NULL) where user_id = NULL;
TRACE commit
``` 

I'm at a loss of what to do, I have googled for answers but did not find anything. What am I doing wrong? I'm not sure it's a library issue but I have run the exact statement successfully in the db console.

**Comment by theogravity** [comment]
I'll take a look at it over the weekend, hard to say if what you're doing is a limitation of the sql template tag or not.

Overall, it feels like a situation where it'd be best to just not use sql template strings.

You should still be able to do parameter binding like you have without it.

**Comment by hannahscript** [comment]
Thank you. I tried that, too, with the same result. I got it working for now by calling run on every statement separated by a semicolon.

**Comment by theogravity** [comment]
This issue is down to the `sqlite3` library itself.

`this.db.run('BEGIN TRANSACTION; INSERT INTO tbl VALUES (?); COMMIT;', ['test'], () => {})`

`this.db` is the `sqlite3` instance and produces your error.

If you do more research into it, it doesn't seem to be supported in a streamlined way.

- [Google search](https://www.google.com/search?q=sqlite3+transaction+node&sxsrf=ALeKk03PKWVMXKvAIT9IAzlCAeO1mp-zcg%3A1621755756280&ei=bAeqYJi6EM64-gS-4IioBA&oq=sqlite3+transaction+node&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEBYQHjIGCAAQFhAeOgcIABBHELADOgcIABCwAxBDOgcIABCHAhAUOgIIADoICAAQFhAKEB5QqzxY8UJgr0VoAXACeACAAVWIAdwDkgEBNpgBAKABAaoBB2d3cy13aXrIAQrAAQE&sclient=gws-wiz&ved=0ahUKEwiYoI_-pt_wAhVOnJ4KHT4wAkUQ4dUDCA4&uact=5)
- [sqlite3 issues](https://github.com/mapbox/node-sqlite3/issues?q=is%3Aissue+is%3Aopen+transaction)
