### ISSUE TITLE
placeholders don't work with pragma

### ISSUE THREAD

**Issue by mugi-luffy** [kriasoft/node-sqlite#149]
db.run('PRAGMA foreign_keys = ?', 'ON')

returns an execption:
[Error: SQLITE_ERROR: near "?": syntax error] {
  errno: 1,
  code: 'SQLITE_ERROR'
}

Is this the expected behaviour? Are placeholders not supposed to work in a pragma?

**Comment by theogravity** [comment]
I've never used pragmas, and am unable to comment on this. 

If you know the fix, please let me know or put up a PR and I can evaluate it from there.

**Comment by mugi-luffy** [comment]
it looks like pragma settings do not support parameters
