### ISSUE TITLE
SQLCipher support

### ISSUE THREAD

**Issue by Christilut** [kriasoft/node-sqlite#150]
I'm using a version of `node-sqlite3` with SQLCipher support but getting it work is an absolute disaster because of all the external dependencies, native modules and requirements of specific node/electron versions.
It would be really amazing if an SQLite library without any dependency like this could support SQLCipher too, I think that would be the perfect solution to this complex problem.

Is there any chance of this happening or anything I could do to help with this? Would be happy to test things for sure.

**Comment by theogravity** [comment]
I don't know anything about the extension you're using, but PRs are always welcome.

**Comment by Christilut** [comment]
Actually I didn't realize that this module runs on `node-sqlite3` so I guess it would have the same problems getting SQLCipher to work.. I thought this was a module without any dependencies which is why I thought it might be a good place to fix this once and for all.
