### ISSUE TITLE
Problem with nullable fields in knex

### ISSUE THREAD

**Issue by SandHilt** [kriasoft/node-sqlite#151]
Hi, I'm having a problem when I'm trying to use it in conjunction with knexjs because some migrations belatedly add non-null fields to the table. For some reason, the package is setting new fields to be null, so it conflicts.
I believe that the sqlite3 package delays migrations by changing only the SQL query and then actually executing it.
How can I replace sqlite3 with this package?
![image](https://user-images.githubusercontent.com/6170125/132234507-b7d7ba10-e129-42f4-99d8-45d07cc88479.png)

**Comment by theogravity** [comment]
Confused. What do you mean by "it", this library or sqlite3?

This library is a wrapper around sqlite3.
