### ISSUE TITLE
Exceptions don't always contain stack traces

### ISSUE THREAD

**Issue by fresheneesz** [kriasoft/node-sqlite#156]
Eg, if I write an invalid query for `get`, the resulting exception contains no stack trace. Pretty unhelpful.

**Comment by theogravity** [comment]
Looking at the impl for it, it's calling the native sqlite3 module and capturing the error that is returned from it.

Not sure if when that module throws, you'd get a stack trace back out of it as it could be a native call to C-land on the sqlite3 side.

You're welcome to put up a PR if you happen to find a way to expose it.

**Comment by fresheneesz** [comment]
TBH, if sqlite3 is returning exceptions without stack traces, this is a bug on their end. That said, its easy enough to fix on this end by simply passing the exception into `new Error`.
