### ISSUE TITLE
Feature: Support ES6 Tagged template literals

### ISSUE THREAD

**Issue by tracker1** [kriasoft/node-sqlite#16]
See: [Tagged template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_template_literals)

example: 

``` javascript
var result = db.get`
  SELECT * 
  FROM demo
  WHERE id = ${this.id}
`;
var results = db.all(`
  ...
`)
```

For implementation...

``` javascript
function all(query, ...values) {
  if (Array.isArray(query)) {
    query = query.join('?');
  } else {
    values = values[0];
  }
  ... original implementation follows ...
}
```

**Comment by GregoryPotdevin** [comment]
I had the same idea a few days ago and thought it would need a babel preprocessor... 
Would love to have this !

**Comment by wmertens** [comment]
In the meantime you can use

```js
// db.all(...S`select * from foo where t = ${bar}`)
export const S = (strings, ...values) => [strings.join('?'), values]
S.json = obj => JSON.stringify(obj)
```

But the proposed approach is of course better. Would also be nice to have an id escape mechanism, since you can't pass e.g. table names as parameters. Options: either inline `SELECT * FROM id${tableName}` or through magic objects `SELECT * FROM ${id(tableName)}`. I think I prefer inline.

**Comment by tracker1** [comment]
@wmertens, would be better to use String objects for enhanced strings...

    db.literal = str => Object.assign(new String(str), { literal: true });

then check for a `.literal` property on a `String`...

**Comment by wmertens** [comment]
True. More obvious, but more typing though ☺

>

**Comment by tracker1** [comment]
var id = db.literal;
    ...
    db.all(`...  ${id(someTableName)} ...`)

Not too bad...

**Comment by theogravity** [comment]
Create a PR w/ unit tests and an updated readme on usage

**Comment by tracker1** [comment]
Will see if I can work on this soon... haven't been working with sqlite lately, so will need to create some test scenarios and get it working.
