### ISSUE TITLE
sqlite api to create a db

### ISSUE THREAD

**Issue by bkyerv** [kriasoft/node-sqlite#167]
I noticed that there is an api/interface to open an existing db, but is there an api to create a db that is mostly used to create and seed a db?

**Comment by theogravity** [comment]
You mean like migrations?

**Comment by bkyerv** [comment]
yes, and I just noticed that despite method being named open it still can create dbs

**Comment by theogravity** [comment]
https://github.com/kriasoft/node-sqlite#migrations ?

**Comment by theogravity** [comment]
Closing as the OP has not responded.
