### ISSUE TITLE
Date and time in db.run

### ISSUE THREAD

**Issue by Damokless** [kriasoft/node-sqlite#169]
Hello,
I would like to write in my gamesLastUpdate column the date and time using datetime('now') except that it doesn't insert in the column and so I always have a null inside 
![image](https://user-images.githubusercontent.com/66098929/207065638-f3f0d0b4-c6ef-4959-9d25-3ed86ab0e2f7.png)
![image](https://user-images.githubusercontent.com/66098929/207065704-30256c2d-7ac1-4115-9960-dca518b95b0f.png)

**Comment by theogravity** [comment]
This isn't a `node-sqlite` issue. I'd raise it with the `sqlite3` project instead.

**Comment by theogravity** [comment]
Another suggestion - does it work if you use double quotes instead of single quote

"INSERT INTO ... datetime('now'))"

**Comment by Damokless** [comment]
```JS
    /* It's checking if the gamesLastUpdate is set. If yes, it will update the gamesLastUpdate. If it's
    not, it will insert the gamesLastUpdate. */
    gamesLastUpdate ? await db.run('UPDATE config SET gamesLastUpdate = datetime(\'now\')') : await db.run('INSERT INTO config(gamesLastUpdate) VALUES(datetime(\'now\'))');
```

this works fine, I think I just defined my column in the database wrong, thanks again for the help
