### ISSUE TITLE
Unable to install Sqlite

### ISSUE THREAD

**Issue by Aci-yt** [kriasoft/node-sqlite#178]
Hi, I've been trying to install sqlite for the past 4 months now, without success.
I used to have no issues using it, but after having to re-install it it simply refuses to.

According to people in the coding den Discord server, there are errors in your codebase (though I know nothing about that)
I'm not even sure what this error is telling me, but I'm starting to think its not on my end.

Any help or advice would be appreciated :)

Since the error message is quite long, I've attached it as a txt file!

[error.txt](https://github.com/kriasoft/node-sqlite/files/13794857/error.txt)

**Comment by theogravity** [comment]
You're probably thinking of the actual library `sqlite3`, which this library is just a wrapper around and dosen't contain any code that needs to be natively compiled.

https://github.com/TryGhost/node-sqlite3

I don't maintain the `sqlite3` library, so you'll want to check there.
