### ISSUE TITLE
Drop the err parameter on the `each` callback

### ISSUE THREAD

**Issue by wmertens** [kriasoft/node-sqlite#19]
The `.each()` call gets a callback for each row, and in sqlite3 that is a node-style callback with `err` always set to null. With promises, it's weird to have err in a callback, especially since it's not used at all.

It would be nice if the signature instead was `db.each(sql, params, function(row) {}).then(...)`.

**Comment by theogravity** [comment]
I thought about this when designing the v4 code, and my original implementation was actually your suggestion. 

In my unit testing, I didn't realize that `sqlite3` does a node-style callback until the test testing it failed, and instead kept the node style callback signature to be consistent with the library.

If you an link me to some proof that `err` is never called, I could change my mind on this.

**Comment by wmertens** [comment]
I think this means that the err is always `null`: https://github.com/mapbox/node-sqlite3/blob/fdceaef843157ee2ff7ce37fe597d199b6c728b9/src/statement.cc#L673
