### ISSUE TITLE
db.serialize() method?

### ISSUE THREAD

**Issue by manikantag** [kriasoft/node-sqlite#20]
Hi, I m trying to use [`db.serialize()`](https://github.com/mapbox/node-sqlite3/wiki/Control-Flow#databaseserializecallback), but I couldn't. From the source code also I see it is not handled.

It is not handled because we can achieve the same with promise chaining or any reason? Thanks.

**Comment by dmm** [comment]
I'm just a user of this library but in my view the functionality of db.serialize() is completely replaced by promise chaining or the equivalent aync/await syntactical sugar.

**Comment by manikantag** [comment]
May be you are correct. Hmm, yeah. In fact I m using async/await with babel, and working fine so far. Closing...
