### ISSUE TITLE
A minor update to TypeScript definitions

### ISSUE THREAD

**Issue by paleo** [kriasoft/node-sqlite#24]
With the current TypeScript definitions, it's not possible to declare a function with a parameter of type `Database` or `Statement`.

Please, update the file `main.d.ts` to export them as interfaces:

    declare module 'sqlite' {
      export interface Statement {
        readonly sql: string;
        readonly lastID: number;
        readonly changes: number;

        bind(): Promise<Statement>;
        bind(...params: any[]): Promise<Statement>;

        reset(): Promise<Statement>;

        finalize(): Promise<void>;

        run(): Promise<Statement>;
        run(...params: any[]): Promise<Statement>;

        get(): Promise<any>;
        get(...params: any[]): Promise<any>;

        all(): Promise<any[]>;
        all(...params: any[]): Promise<any[]>;

        each(callback?: (err: Error, row: any) => void): Promise<number>;
        each(...params: any[]): Promise<number>;
      }

      export interface Database {
        close(): Promise<void>;

        run(sql: string): Promise<Statement>;
        run(sql: string, ...params: any[]): Promise<Statement>;

        get(sql: string): Promise<any>;
        get(sql: string, ...params: any[]): Promise<any>;

        all(sql: string): Promise<any[]>;
        all(sql: string, ...params: any[]): Promise<any[]>;

        exec(sql: string): Promise<Database>;

        each(sql: string, callback?: (err: Error, row: any) => void): Promise<number>;
        each(sql: string, ...params: any[]): Promise<number>;

        prepare(sql: string): Promise<Statement>;
        prepare(sql: string, ...params: any[]): Promise<Statement>;

        migrate(options: { force?: boolean, table?: string, migrationsPath?: string }): Promise<Database>;
      }

      export function open(filename: string, options?: { mode?: number, verbose?: boolean, promise?: typeof Promise }): Promise<Database>;
      export default { open }
    }

Notice: I leave the last line `export default { open }` but it is invalid. There is actually no member `default` in the module. I think it should be removed.

**Comment by stahlstift** [comment]
Yep, we really need this!

**Comment by theogravity** [comment]
Do you want to create a PR and I'll merge it in? seems harmless to do

**Comment by taumechanica** [comment]
These changes among other things are suggested as PR #26. Thanks.

**Comment by theogravity** [comment]
Published under `2.4.0`

**Comment by theogravity** [comment]
Correction `2.5.0` (2.4.0 was incorrectly packaged)
