### ISSUE TITLE
BUG: Database.migrate() removes useful lines from scripts

### ISSUE THREAD

**Issue by BeLi4L** [kriasoft/node-sqlite#27]
### Description

If a migration script contains a line which starts with `--` which is inside an actual string value, it will be considered as a comment and thus removed from the eventual script.

### Steps to reproduce

Considering this migration script:

```sql
-- Up
CREATE TABLE whatever ( certificate TEXT );
INSERT INTO whatever ( certificate ) VALUES (
  '-----BEGIN CERTIFICATE-----
some contents
-----END CERTIFICATE-----');

-- Down
DROP TABLE whatever;
```

calling `db.migrate()` will fail due to a syntax error

### Explanation
Calling `db.migrate()` will parse the up script, and will remove the line `-----END CERTIFICATE-----');` because it starts with `--`. 

Code which causes this problem: https://github.com/kriasoft/node-sqlite/blob/master/src/Database.js#L170
 ```js
migration.up = up.replace(/^--.*?$/gm, '').trim();
```

**Comment by theogravity** [comment]
Published under `2.6.0`
