### ISSUE TITLE
How to trace SQL errors?

### ISSUE THREAD

**Issue by tad-lispy** [kriasoft/node-sqlite#31]
I'm getting unhelpful error:

```
{ Error: SQLITE_RANGE: bind or column index out of range

 errno: 25, code: 'SQLITE_RANGE' }
```

How can I trace it? According to [the documentation of node-sqlite3](https://github.com/mapbox/node-sqlite3/wiki/Debugging#databaseontrace-callback) I can attach a callback to `trace` event to see the SQL being sent to the DB, but your wrapper doesn't seem to have `on` method:

```
TypeError: db.on is not a function
```

**Comment by lzrski** [comment]
Oh, I think I found it! The underlaying `node-sqlite3` instance is exposed as `Database.driver`, so assuming that it's bound to `db` it is possible to do:

```
db.driver.on('trace', console.log)
```

Perhaps it should be documented in the ReadMe?

**Comment by theogravity** [comment]
Feel free to create a PR for the docs

**Comment by theogravity** [comment]
added to the v4 beta readme
