### ISSUE TITLE
Suggestion: tell about building

### ISSUE THREAD

**Issue by Hibou57** [kriasoft/node-sqlite#33]
SQLite3 Node module can be built with an sqlite3.h and a libsqlite3.so. It's convenient to get the latest SQLite3 version (ex. the actual is 3.19.2, and I built the library with the amalgation C file).

I’ve just checked the same can be done with the promisified SQLite module:

    npm install -g --build-from-source --sqlite=/<some-dir>/sqlite3 sqlite

It works.

This may be useful to users to tell about this option.

**Comment by theogravity** [comment]
Feel free to open a PR adding to the readme

**Comment by theogravity** [comment]
v4 now allows for any sqlite library to be used as long as it conforms to the `sqlite3` API. You might want to check it out.
