### ISSUE TITLE
Error after installing sqlite and another package afterwards

### ISSUE THREAD

**Issue by tiehm** [kriasoft/node-sqlite#37]
When installing sqlite and installing another package afterwards you get his error:

npm ERR! path D:\Users\charl\Desktop\Desktop\General\Dektop 2\test\node_modules\.staging\npmlog-3d453044
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'D:\Users\charl\Desktop\Desktop\General\Dektop 2\test\node_modules\.staging\npmlog-3d453044' -> 'D:\Users\charl\Desktop\Desktop\General\Dektop 2\test\node_modules\sqlite3\node_modules\node-pre-gyp\node_modu
les\npmlog'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\charl\AppData\Roaming\npm-cache\_logs\2017-08-25T22_48_05_520Z-debug.log

When starting an app you will get the error: Cannot find module 'npmlog'

**Comment by theogravity** [comment]
Closing as there hasn't been any new info on this and it looks related to `sqlite3`, which we do not maintain
