### ISSUE TITLE
How to open a database as readonly?

### ISSUE THREAD

**Issue by briangonzalez** [kriasoft/node-sqlite#39]
cc/ @wtfaremyinitials

**Comment by theogravity** [comment]
the 2nd param to `open` 

```
import sqlite3 from 'sqlite';

const dbPromise = sqlite.open('./database.sqlite', { 
Promise 
mode: sqlite3.OPEN_READONLY
});
```

see https://github.com/mapbox/node-sqlite3/wiki/API#new-sqlite3databasefilename-mode-callback

**Comment by briangonzalez** [comment]
Perfect, thanks!

**Comment by msikma** [comment]
I assume that the above code should say `import sqlite3 from 'sqlite3'`? Like you need to get the `OPEN_READONLY` etc. constants from the parent package, not from `sqlite` directly? Because I'm trying to do this as well, but I can't figure out how to do it with only the `sqlite` package.

**Comment by linzyjx** [comment]
> the 2nd param to `open`
> 
> ```
> import sqlite3 from 'sqlite';
> 
> const dbPromise = sqlite.open('./database.sqlite', { 
> Promise 
> mode: sqlite3.OPEN_READONLY
> });
> ```
> 
> see https://github.com/mapbox/node-sqlite3/wiki/API#new-sqlite3databasefilename-mode-callback

Using this code will cause my environment to report errors and fail to implement the function.

The following code works well:

```
import sqlite from 'sqlite';
import sqlite3 from 'sqlite3';

let db = await sqlite.open(':memory:',
    {
        mode: sqlite3.OPEN_READONLY
    }
);
```
