### ISSUE TITLE
Example using multiple databases.

### ISSUE THREAD

**Issue by tracker1** [kriasoft/node-sqlite#4]
Would be nice to see an example with a context where multiple db instances can be created to different backing files.

**Comment by koistya** [comment]
@tracker1 good question! Here is an example how to work with multiple databases:

```js
import sqlite from 'sqlite';
import bluebird from 'bluebird';

const coreDb = sqlite.open('./core.sqlite', { Promise });
const dataDb = sqlite.open('./data.sqlite', { Promise });

coreDb.get('SELECT * FROM Table WHERE id = ?', 123).then(row => console.log(row));
```

I guess it would be good to include that info into `README.md`. A [pull request](https://help.github.com/articles/using-pull-requests/) is more than welcome!

**Comment by adek05** [comment]
How to run two different migrations against different tables open?

**Comment by theogravity** [comment]
I've documented this in the v4 beta readme, thanks all
