### ISSUE TITLE
Need documentation for migrate.

### ISSUE THREAD

**Issue by alvaro1728** [kriasoft/node-sqlite#41]
Hi,

I just started using this library and it's great.  The only thing it's lacking is more documentation on the **migrate** function.  Can you please document what each of its parameter mean and also how _migration.sql_ files are read and what the Up/Down sections actually mean.

Thanks!
Alvaro

**Comment by dweremeichik** [comment]
Even some quick pointers would be good.

**Comment by theogravity** [comment]
I know this isn't that great, but this has an example

https://github.com/kriasoft/node-sqlite/issues/11

**Comment by theogravity** [comment]
The `up` section means when you want to migrate to the next/current version of your schema. The `down` section means if you were to undo the migration, this is the SQL to execute.

The migration signature looks like this:

`async migrate({ force, table = 'migrations', migrationsPath = './migrations' } = {})`

Out of those three options, I'd say you'd care most about `migrationsPath`, which would be the directory containing your migration files.

If `force` is set to `last`, then the `down` section would get executed in the most recent migration file. It doesn't seem to do anything else (you'd figure that `force` is a bool, but looking at the code, it's not).

https://github.com/kriasoft/node-sqlite/blob/89b4404d8fb39eb21977ae250e05e7c6b51113bc/src/Database.js#L204

**Comment by dweremeichik** [comment]
Thanks @theogravity I'll see if I can submit a PR sometime this week.

**Comment by theogravity** [comment]
Check out the v4 beta, which should have this properly documented with a slight change.
