### ISSUE TITLE
Pre-built binaries url down?

### ISSUE THREAD

**Issue by Kxze** [kriasoft/node-sqlite#50]
When running `npm i --save sqlite` I get a 403 error when trying to download the pre-build binaries from https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v59-win32-x64.tar.gz. According to http://isup.me it's not just me.

**Comment by theogravity** [comment]
We don't maintain / build the sqlite3 binaries. This project is only a wrapper around it. 

https://github.com/mapbox/node-sqlite3

You'll want to post an issue there regarding it.

**Comment by Kxze** [comment]
Will do, thanks.
