### ISSUE TITLE
db.serialize missing

### ISSUE THREAD

**Issue by johan13** [kriasoft/node-sqlite#54]
I am missing `db.serialize` from sqlite3. According to a previous issue (#20) `db.serialize` can be replaced by promise chaining, but I don't see how.

Consider this code:
```javascript
const sqlite = require("sqlite");

main().catch(console.error);

async function main() {
    const db = await sqlite.open(":memory:");
    await db.exec("CREATE TABLE foo (name TEXT)");

    await Promise.all([alpha(db), beta(db)]);

    console.log(await db.all("SELECT name FROM foo"));
}

async function alpha(db) {
    await db.exec("BEGIN TRANSACTION");
    await db.exec("INSERT INTO foo VALUES ('alpha')");
    await db.exec("ROLLBACK TRANSACTION");
}

async function beta(db) {
    await db.exec("INSERT INTO foo VALUES ('beta')");
}
```

This will print `[]` and not `[ { name: 'beta' } ]` because the `beta` method will be included in `alpha`'s transaction. Can I keep alpha and beta separate without `db.serialize`? In this contrived example I think I could just merge the three calls to `db.exec` into one but if there is other code between the calls to `db.exec` then that is not an option.

**Comment by johan13** [comment]
Maybe it isn't as simple as adding a `db.serialize` method. It seems I would also need to use the synchronous version of `db.exec` (which also isn't exposed in `node-sqlite`). According to https://github.com/mapbox/node-sqlite3/wiki/Control-Flow _queries scheduled not directly in the callback function are not necessarily serialized_.

With this primitive implementation of serialize:
```javascript
function serialize(db, cb) {
    return new Promise((resolve, reject) => {
        db.driver.serialize(function() {
            cb().then(resolve).catch(reject);
        });
    });
}
```

then this still wouldn't be serialized:
```javascript
async function alpha(db) {
    await serialize(db, async () => {
        await db.exec("BEGIN TRANSACTION");
        await db.exec("INSERT INTO foo VALUES ('alpha')");
        await db.exec("ROLLBACK TRANSACTION");
    });
}
```

but this would be:
```javascript
async function alpha(db) {
    await serialize(db, async () => {
        db.driver.exec("BEGIN TRANSACTION");
        db.driver.exec("INSERT INTO foo VALUES ('alpha')");
        db.driver.exec("ROLLBACK TRANSACTION");
    });
}
```

Any ideas for a workaround?

**Comment by theogravity** [comment]
I'm unfortunately not familiar with serial execution in sqlite. Can definitely start out my exposing the serialize method to the node-sqlite API if you want to open a PR to add it in.

It also sounds like a question to ask in the sqlite3 repo since this lib just generally wraps the sqlite3 API with promises.

**Comment by johan13** [comment]
I started working on a PR for a serialize method - that was how I realized that exposing serialize wasn't going to be enough. 😕

I will continue to investigate this a bit...

**Comment by johan13** [comment]
It turs out that I had misunderstood the role of serialize. The solution is to open a separate db connection for the transaction. I will close this issue.

**Comment by theDevelopper** [comment]
@johan13 can you give an example of your finding? Could such a case maybe added as an example to the documentation?

**Comment by KpjComp** [comment]
A separate db connection to me seems overkill for db serialisation.

If your serialisation code is fast, and generally that's the ideal transaction schema.  Then a nice solution is just using a queue with a concurrency of 1.

I'm no SQLite internal expert, but I would also assume separate db connections are also going to void any cache mechanisms.
