### ISSUE TITLE
Add REGEXP support

### ISSUE THREAD

**Issue by Rastanislav** [kriasoft/node-sqlite#55]
Hello, is it possible to add the regexp() support out of the box?
Or if there is a way to add it from other source please provide some info.
SQLITE_ERROR: no such function: regexp

Thanks

**Comment by theogravity** [comment]
Can you give an example of how it should be used / defined in the library?

**Comment by xfix** [comment]
It's necessary to define a function called `regexp`, see https://www.sqlite.org/c3ref/create_function.html, taking two arguments, the first one being regular expression, the second one being text to match.

**Comment by antoni-g** [comment]
If I'm not mistaken, this issue references this in the original mapbox implementation:

https://github.com/xpbrew/cordova-sqlite-storage/issues/741

**Comment by theogravity** [comment]
This is a non-native extension, but the v4 beta has the `loadExtension` method from `sqlite3` that you might want to check out.

**Comment by lixingyangok** [comment]
> loadExtension

Is there usage for loadExtension() please?
I am trying to make the sqlite3 can use regexp,
but I haven't found the information of loadExtension in Document 😂😂😂
Thanks a lot, Thanks a lot,
