### ISSUE TITLE
Installation fails with node10

### ISSUE THREAD

**Issue by NoahHydro** [kriasoft/node-sqlite#58]
npm install sqlite gives the following error:

`../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'`

**Comment by thiago-dev** [comment]
> The problem here is that V8 has removed ForceSet method in the V8 version that Node 10 uses, which > in turn is what the nan module uses. nan has not yet caught up to the breaking changes in V8.
source: https://stackoverflow.com/a/50112270

solved it with:
`npm shrinkwrap
`
edit npm-shrinkwrap.json and modify/add sqlite
`
"dependencies": {
"sqlite": {
      "version": "^2.9.1",
      "dependencies": {
        "sqlite3": { "version": "^4.0.0"}
      }
}
`

**Comment by theogravity** [comment]
There's a PR up with the update 4.0.0 - I'll test / merge it tonight if possible

**Comment by theogravity** [comment]
new package has been updated
