### ISSUE TITLE
BYO sqlite3 (support sqlite3-offline)

### ISSUE THREAD

**Issue by iffy** [kriasoft/node-sqlite#59]
I like `node-sqlite` but I keep having trouble building sqlite in my Electron app.  I'd like to try using [sqlite3-offline](https://www.npmjs.com/package/sqlite3-offline) but there's not a good way to use `node-sqlite` with anything other than the `sqlite3` package.

I can submit a pull request, but before I do the work, I'd like to know what you think about making `sqlite3` an optional dependency of this package.  Or perhaps splitting this package into 2:

1. This package (bundled with `sqlite3`) which depends on a new package:
2. A package that implements all the promise-adding but doesn't depend on `sqlite3`

**Comment by theogravity** [comment]
Making the `sqlite3` package optional is probably the way to go, where the init would take in the sqlite driver to use.

This would probably warrant a new major release as it'd break backwards-compat

**Comment by theogravity** [comment]
v4 beta now supports plugging in alternative sqlite libraries that conform to the `sqlite3` interface. I did a very basic test with `sqlite3-offline` and didn't find any immediate issues.
