### ISSUE TITLE
Feature requests for v3?

### ISSUE THREAD

**Issue by theogravity** [kriasoft/node-sqlite#62]
If a v3 was to be developed, what features would you want?

- Ability to use any sqlite driver

**Comment by MingweiSamuel** [comment]
Something I wish `node-sqlite3` had is a constructor that takes in a buffer containing the sqlite3 data because I have a use case where I'm reading sqlite3 files from inside a zip

**Comment by theogravity** [comment]
We do not maintain `sqlite3`, and if that doesn't support it, we wouldn't be able to.

v4 beta is out, closing this thread.
