### ISSUE TITLE
Run method should resolve with the statement object

### ISSUE THREAD

**Issue by theogravity** [kriasoft/node-sqlite#7]
When doing an insert/update using `run()`, I'm unable to get the status of the execution back as noted in:

https://github.com/mapbox/node-sqlite3/wiki/API#databaserunsql-param--callback

```
 The context of the function (the this object inside the function) is the statement object. 
```

The problem:
https://github.com/kriasoft/node-sqlite/blob/master/src/Database.js#L43

The callback is using the arrow function, so `this` is the reference to the class instance itself instead of the statement object

**Comment by koistya** [comment]
This should do the trick, right?

```js
  run(...params) {
    return new this.Promise((resolve, reject) => {
      const Promise = this.Promise;
      this.stmt.run(...params, function (err) {
        if (err) {
          reject(err);
        } else {
          resolve(new Statement(this, Promise));
        }
      });
    });
  }
```

**Comment by theogravity** [comment]
Yes, i'll have a pr for you in a second

**Comment by theogravity** [comment]
Your proposed fix won't work because you shouldn't be returning an instance of the `node-sqlite` Statement; instead, it should be the one from `sqlite3`, which is set via the context.

See my PR for the fix.

**Comment by dtrebbien** [comment]
Note: In @121359f, I propose resolving to the same node-sqlite `Statement` object. I presume that when you write that this "won't work", that you are referring to the (at the time) unavailability of `lastID` and `changes`. In that commit, I add getters to retrieve the values from the underlying driver statement object.

**Comment by theogravity** [comment]
Given that it's only the `run` method that applies, I don't think `Statement` should expose the specific id/changes property for all execution types. Maybe have a method to return the `sqlite3` statement object instead if needed?
