### ISSUE TITLE
the dependent 'sqlite3@4.0.0' can't be installed, please update

### ISSUE THREAD

**Issue by dawangraoming** [kriasoft/node-sqlite#70]
the `sqlite3@4.0.0` has some problems with installation, please update to `4.0.1`, thanks.

https://github.com/mapbox/node-sqlite3/issues/961

**Comment by AxelTerizaki** [comment]
4.0.2 is out, and fixes those problems.

See mapbox/node-sqlite3#1010

I'll try to make a PR today for that change
