### ISSUE TITLE
Error while i'm creating tables

### ISSUE THREAD

**Issue by Drylotrans** [kriasoft/node-sqlite#72]
While i'm creating tables with sqlite, i get an error
View my code:
```js
var sql = require('sqlite')
sql.open('./db.sqlite')
sql.run("CREATE TABLE IF NOT EXISTS users (id INTEGER, diner INTEGER)")
```
View the error: 
```js
TypeError: Cannot read property 'run' of null
```
I say it to a friend, and he says me that he receives the same

**Comment by theogravity** [comment]
the open call returns a database instance, you would call `run` against that.

I would check out the v4 beta which has plenty of examples now
