### ISSUE TITLE
TypeError: db.get is not a function

### ISSUE THREAD

**Issue by T1MOXA** [kriasoft/node-sqlite#75]
I get an error when I try to run a query.

Code:
```js
const sqlite = require('sqlite');
const db = sqlite.open('./database.sqlite');

db.get(`SELECT * FROM database`).then((result) => {
	console.log(result);
});
```
What am I doing wrong ?

**Comment by T1MOXA** [comment]
This design helped:
```
let dbn;
(async () => {
	dbn = await sqlite.open('./database.sqlite', { Promise });
})();
```
But I don't really like this decision.
Can I do it more elegantly ?

**Comment by theogravity** [comment]
What you want is a top-level await, but that is not supported yet in node. It would make the above less ugly to write for sure.
