### ISSUE TITLE
How to get affected rows by db.all query ?

### ISSUE THREAD

**Issue by T1MOXA** [kriasoft/node-sqlite#76]
When i execute db.all query I don't get a "Statement" object and therefore can't get the number of rows affected.
Is it a bug or am I doing something wrong ?

**Comment by theogravity** [comment]
`Database#all` does not return a `Statement` object in the `sqlite3` API, so this is not supported. You might want to use a method that does, such as `Database#run` / `Database#prepare`

https://github.com/mapbox/node-sqlite3/wiki/API#databaseallsql-param--callback
