### ISSUE TITLE
SQLite Release 3.25.0 On 2018-09-15

### ISSUE THREAD

**Issue by paulvanvulpen** [kriasoft/node-sqlite#83]
Hi, I was wondering if you are planning to support SQlite 3.25? The Window Function would be very helpful.

**Comment by meisterlampe** [comment]
SQlite 3.25 would be nice (I like the new rename table-column command ;) )

**Comment by theogravity** [comment]
This library uses `sqlite3` under the hood, and the semver rules we use should pick up the latest 4.0.x version. If you need a specific version supported, you need to ask the sqlite3 team to support it.

**Comment by kewde** [comment]
sqlite3 uses 3.26. Can be closed.
