### ISSUE TITLE
Question: TypeScript sqlite example projects

### ISSUE THREAD

**Issue by morgrowe** [kriasoft/node-sqlite#87]
I can see types have been [added to this project](https://github.com/kriasoft/node-sqlite/pull/21), but for the life of me, I can't work out why VSCode is complaining about sqlite all the time. I'm new to TypeScript and this project, so I'm more than likely using them incorrectly. Is anyone aware of any projects using sqlite with TypeScript? Would like to look at the source code to see some examples.

Apologies for making an 'issue' for a question--I don't know where else to ask.

Cheers

**Comment by acharyarupak391** [comment]
@morgrowe did u find anything on this? I'm facing same issue 🥲
