### ISSUE TITLE
Using node-sqlite with ElectronApp

### ISSUE THREAD

**Issue by aashna208** [kriasoft/node-sqlite#95]
Hi,

I'm trying to use node-sqlite in electronApp but it won't use the native binaries for sqlite3 and default to binaries build for node. I get the following error:

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/aashna/lobe/2_lobe/lobe/app/server/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node
  Expected in: flat namespace

Is there anything I'm missing here?

**Comment by theogravity** [comment]
This is an issue specific to `sqlite3` and should probably be posted in that repository.

You might want to try the v4 beta where you can use a different version of `sqlite3`.
