### ISSUE TITLE
Is it possible to enable the underlying node-sqlite3's verbose mode?

### ISSUE THREAD

**Issue by scottdotjs** [kriasoft/node-sqlite#96]
`node-sqlite3` has a verbose mode (covered at [their debugging page](https://github.com/mapbox/node-sqlite3/wiki/Debugging)) but I don't know if I can get to it through this interface.

**Comment by theogravity** [comment]
Feel free to open a PR to include it

**Comment by theogravity** [comment]
Oh, I found this:

```
    await sqlite.open(this.config.path, { verbose: true })
```

**Comment by theogravity** [comment]
v4 of `sqlite` now has explicit instructions on how to do this
