### ISSUE TITLE
Where is the `this` object?

### ISSUE THREAD

**Issue by zwhitchcox** [kriasoft/node-sqlite#97]
There is a `this` object that is called when inserting a row  that contains the `lastID`, useful for inserting rows. However `await db.run("INSERT INTO...")` returns undefined.

Is there a way to access the this object that is returned by `sqlite3`?

**Comment by theogravity** [comment]
you should be able to via `db.lastId`, since I see this

```
  get lastID() {
    return this.stmt.lastID;
  }
```

**Comment by theogravity** [comment]
Try the v4 beta which should address this problem.
